services:
  # Servidor Web (Nginx)
  web:
    image: nginx:alpine
    container_name: web_server
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  # Motor PHP 8.4 + Drivers PostgreSQL
  app:
    build: .
    container_name: php_engine
    volumes:
      - ./src:/var/www/html

  # Base de Datos (PostgreSQL 17)
  db:
    image: postgres:17-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: aalmonte
      POSTGRES_PASSWORD: mosango0106
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: